export default theme => ({
   diceRoller: {
      width: '100%',
      minHeight: 100,
      maxHeight: 300,
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'space-between',
      color: '#fff',
      padding: [6, 3],
      position: 'absolute',
      bottom: 0,
   },
   input: {
      width: '100%',
      height: '50%',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      '& .input-header': {
         display: 'flex',
         '& .die-type': {
            width: 20,
            height: 16,
            fontSize: 10,
            padding: 0,
            textAlign: 'center',
         },
      },
      '& .input-content': {
         width: '100%',
         display: 'flex',
         padding: [0, 10],
         marginTop: 3,
         '& input': {
            width: '75%',
            borderRadius: [3, 0, 0, 3],
         },
         '& button': {
            width: '25%',
            height: 24,
            background: 'none',
            color: '#11b5bb',
            border: [1, 'solid', '#11b5bb'],
            borderLeft: [1, 'solid', theme.eliteOrange],
            borderRadius: [0, 3, 3, 0],
            marginLeft: -1,
            outline: 'none',
            cursor: 'pointer',
         },
      },
   },
   results: {
      width: '100%',
      height: '50%',
      maxHeight: 200,
      display: 'flex',
      flexDirection: 'column',
      padding: [0, 10],
      margin: [20, 0],
      '& .total': {
         display: 'flex',
         justifyContent: 'center',
         marginBottom: 6,
         color: '#00fa21',
      },
      '& .die': {
         width: '100%',
         height: '100%',
         maxHeight: 180,
         display: 'flex',
         justifyContent: 'center',
         flexWrap: 'wrap',
         overflowY: 'scroll',
         '& div': {
            margin: [0, 10, 10, 10],
         },
         '&::-webkit-scrollbar': {
            width: 2
         },
         '&::-webkit-scrollbar-thumb': {
            background: '#fff',
            '-webkit-border-radius': 1,
            '-webkit-box-shadow': 'inset 0 0 6px rgba(0, 0, 0, 0.3)',
         },
      },
   },
});